#!/bin/bash

# validate-after-fallback.sh
# Enhanced validation for code generated by free/offline AI models
# Enforces STRICT rules (hard block) and warns on FLEXIBLE rules

set -euo pipefail

# Color output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
VERBOSE=false
STRICT_ONLY=false
FLEXIBLE_ONLY=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --verbose)
      VERBOSE=true
      shift
      ;;
    --strict-only)
      STRICT_ONLY=true
      shift
      ;;
    --flexible-only)
      FLEXIBLE_ONLY=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--verbose] [--strict-only] [--flexible-only]"
      exit 1
      ;;
  esac
done

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🔍 Enhanced Validation (Free/Offline Models)${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

STRICT_VIOLATIONS=0
FLEXIBLE_WARNINGS=0

# ============================================
# STRICT RULES (Hard Block)
# ============================================

if [[ "$FLEXIBLE_ONLY" == "false" ]]; then
  echo -e "${BLUE}STRICT RULES (Hard Block):${NC}"
  echo ""

  # Rule 1: Design Token Compliance
  echo -n "  Design Tokens: "
  TOKEN_VIOLATIONS=$(npm run lint --silent 2>&1 | grep "@dcyfr/no-hardcoded-values" | wc -l || echo "0")
  TOKEN_VIOLATIONS=$(echo "$TOKEN_VIOLATIONS" | tr -d ' ')
  
  if [[ "$TOKEN_VIOLATIONS" -eq 0 ]]; then
    echo -e "${GREEN}✅ 0 violations${NC}"
  else
    echo -e "${RED}❌ $TOKEN_VIOLATIONS violations${NC}"
    STRICT_VIOLATIONS=$((STRICT_VIOLATIONS + TOKEN_VIOLATIONS))
    
    if [[ "$VERBOSE" == "true" ]]; then
      echo ""
      npm run lint --silent 2>&1 | grep "@dcyfr/no-hardcoded-values" || true
      echo ""
    fi
  fi

  # Rule 2: PageLayout Usage (90% rule)
  echo -n "  PageLayout Usage: "
  TOTAL_PAGES=$(find app -name "page.tsx" -type f | wc -l | tr -d ' ')
  PAGELAYOUT_USAGE=$(grep -r "<PageLayout" app --include="page.tsx" | wc -l | tr -d ' ')
  
  if [[ "$TOTAL_PAGES" -eq 0 ]]; then
    COMPLIANCE=100
  else
    COMPLIANCE=$(echo "scale=2; $PAGELAYOUT_USAGE / $TOTAL_PAGES * 100" | bc)
  fi
  
  COMPLIANCE_INT=${COMPLIANCE%.*}
  
  if [[ "$COMPLIANCE_INT" -ge 90 ]]; then
    echo -e "${GREEN}✅ ${COMPLIANCE}% (target: ≥90%)${NC}"
  else
    echo -e "${RED}❌ ${COMPLIANCE}% (target: ≥90%)${NC}"
    STRICT_VIOLATIONS=$((STRICT_VIOLATIONS + 1))
    
    if [[ "$VERBOSE" == "true" ]]; then
      echo ""
      echo "  Pages missing PageLayout:"
      find app -name "page.tsx" -type f -exec grep -L "<PageLayout" {} \; || true
      echo ""
    fi
  fi

  # Rule 3: Barrel Export Imports
  echo -n "  Barrel Exports: "
  DEEP_IMPORTS=$(npm run lint --silent 2>&1 | grep "@dcyfr/no-deep-imports" | wc -l || echo "0")
  DEEP_IMPORTS=$(echo "$DEEP_IMPORTS" | tr -d ' ')
  
  if [[ "$DEEP_IMPORTS" -eq 0 ]]; then
    echo -e "${GREEN}✅ 0 violations${NC}"
  else
    echo -e "${RED}❌ $DEEP_IMPORTS violations${NC}"
    STRICT_VIOLATIONS=$((STRICT_VIOLATIONS + DEEP_IMPORTS))
    
    if [[ "$VERBOSE" == "true" ]]; then
      echo ""
      npm run lint --silent 2>&1 | grep "@dcyfr/no-deep-imports" || true
      echo ""
    fi
  fi

  # Rule 4: Test Data Prevention
  echo -n "  Test Data Prevention: "
  TEST_DATA_IN_SRC=$(grep -r "FABRICATED\|TEST_DATA\|MOCK_" src --include="*.ts" --include="*.tsx" --exclude="*.test.*" 2>/dev/null | wc -l || echo "0")
  TEST_DATA_IN_SRC=$(echo "$TEST_DATA_IN_SRC" | tr -d ' ')
  
  if [[ "$TEST_DATA_IN_SRC" -eq 0 ]]; then
    echo -e "${GREEN}✅ 0 violations${NC}"
  else
    echo -e "${RED}❌ $TEST_DATA_IN_SRC violations${NC}"
    STRICT_VIOLATIONS=$((STRICT_VIOLATIONS + TEST_DATA_IN_SRC))
    
    if [[ "$VERBOSE" == "true" ]]; then
      echo ""
      grep -rn "FABRICATED\|TEST_DATA\|MOCK_" src --include="*.ts" --include="*.tsx" --exclude="*.test.*" 2>/dev/null || true
      echo ""
    fi
  fi

  # Rule 5: Emoji Usage
  echo -n "  Emoji Usage: "
  # Unicode emoji ranges (simplified check)
  EMOJI_IN_UI=$(grep -r "🎯\|🚀\|✨\|💡\|🔥\|📝\|✅\|❌\|⚠️" src app --include="*.tsx" --include="*.md" --exclude="*.test.*" 2>/dev/null | wc -l || echo "0")
  EMOJI_IN_UI=$(echo "$EMOJI_IN_UI" | tr -d ' ')
  
  if [[ "$EMOJI_IN_UI" -eq 0 ]]; then
    echo -e "${GREEN}✅ 0 violations${NC}"
  else
    echo -e "${RED}❌ $EMOJI_IN_UI violations${NC}"
    STRICT_VIOLATIONS=$((STRICT_VIOLATIONS + EMOJI_IN_UI))
    
    if [[ "$VERBOSE" == "true" ]]; then
      echo ""
      grep -rn "🎯\|🚀\|✨\|💡\|🔥\|📝\|✅\|❌\|⚠️" src app --include="*.tsx" --include="*.md" --exclude="*.test.*" 2>/dev/null || true
      echo ""
    fi
  fi

  echo ""
fi

# ============================================
# FLEXIBLE RULES (Warn Only)
# ============================================

if [[ "$STRICT_ONLY" == "false" ]]; then
  echo -e "${BLUE}FLEXIBLE RULES (Warn Only):${NC}"
  echo ""

  # Rule 6: API Pattern Adherence
  echo -n "  API Patterns: "
  TOTAL_POSTS=$(find app/api -name "route.ts" -type f -exec grep -l "export async function POST" {} \; 2>/dev/null | wc -l || echo "0")
  INNGEST_USAGE=$(find app/api -name "route.ts" -type f -exec grep -l "inngest.send" {} \; 2>/dev/null | wc -l || echo "0")
  TOTAL_POSTS=$(echo "$TOTAL_POSTS" | tr -d ' ')
  INNGEST_USAGE=$(echo "$INNGEST_USAGE" | tr -d ' ')
  
  if [[ "$TOTAL_POSTS" -eq 0 ]]; then
    INNGEST_RATIO=100
  else
    INNGEST_RATIO=$(echo "scale=2; $INNGEST_USAGE / $TOTAL_POSTS * 100" | bc)
  fi
  
  INNGEST_RATIO_INT=${INNGEST_RATIO%.*}
  
  if [[ "$INNGEST_RATIO_INT" -ge 80 ]]; then
    echo -e "${GREEN}✅ ${INNGEST_RATIO}% Inngest usage (target: ≥80%)${NC}"
  else
    echo -e "${YELLOW}⚠️  ${INNGEST_RATIO}% Inngest usage (target: ≥80%)${NC}"
    FLEXIBLE_WARNINGS=$((FLEXIBLE_WARNINGS + 1))
    
    if [[ "$VERBOSE" == "true" ]]; then
      echo ""
      echo "  POST routes without Inngest:"
      find app/api -name "route.ts" -type f -exec grep -L "inngest.send" {} \; 2>/dev/null || true
      echo ""
    fi
  fi

  # Rule 7: Test Coverage Quality
  echo -n "  Test Coverage: "
  
  # Run tests in silent mode to get pass rate
  if npm run test:run --silent > /tmp/test-output.txt 2>&1; then
    TEST_PASS_RATE=100
  else
    # Parse test output for pass rate
    PASSED=$(grep -o "[0-9]* passed" /tmp/test-output.txt | grep -o "[0-9]*" || echo "0")
    FAILED=$(grep -o "[0-9]* failed" /tmp/test-output.txt | grep -o "[0-9]*" || echo "0")
    TOTAL=$((PASSED + FAILED))
    
    if [[ "$TOTAL" -eq 0 ]]; then
      TEST_PASS_RATE=100
    else
      TEST_PASS_RATE=$(echo "scale=2; $PASSED / $TOTAL * 100" | bc)
    fi
  fi
  
  TEST_PASS_RATE_INT=${TEST_PASS_RATE%.*}
  
  if [[ "$TEST_PASS_RATE_INT" -ge 99 ]]; then
    echo -e "${GREEN}✅ ${TEST_PASS_RATE}% pass rate (target: ≥99%)${NC}"
  else
    echo -e "${YELLOW}⚠️  ${TEST_PASS_RATE}% pass rate (target: ≥99%)${NC}"
    FLEXIBLE_WARNINGS=$((FLEXIBLE_WARNINGS + 1))
    
    if [[ "$VERBOSE" == "true" ]]; then
      echo ""
      cat /tmp/test-output.txt | grep "FAIL\|✕" || true
      echo ""
    fi
  fi

  echo ""
fi

# ============================================
# SUMMARY & EXIT
# ============================================

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if [[ "$STRICT_VIOLATIONS" -eq 0 ]] && [[ "$FLEXIBLE_WARNINGS" -eq 0 ]]; then
  echo -e "${GREEN}✅ VALIDATION PASSED${NC}"
  echo "   All STRICT rules pass, no FLEXIBLE warnings"
  echo ""
  exit 0
elif [[ "$STRICT_VIOLATIONS" -eq 0 ]] && [[ "$FLEXIBLE_WARNINGS" -gt 0 ]]; then
  echo -e "${YELLOW}⚠️  WARNINGS (Manual Review Required)${NC}"
  echo "   STRICT rules: ✅ Pass"
  echo "   FLEXIBLE warnings: $FLEXIBLE_WARNINGS"
  echo ""
  echo "📋 MANUAL CHECKLIST:"
  
  if [[ "$INNGEST_RATIO_INT" -lt 80 ]]; then
    echo "   - [ ] Review API routes without Inngest (acceptable for simple operations)"
  fi
  
  if [[ "$TEST_PASS_RATE_INT" -lt 99 ]]; then
    echo "   - [ ] Investigate test failures (see verbose output)"
  fi
  
  echo ""
  echo "See: .opencode/enforcement/VALIDATION_ENHANCED.md"
  echo ""
  exit 0
else
  echo -e "${RED}❌ VALIDATION FAILED (HARD BLOCK)${NC}"
  echo "   STRICT violations: $STRICT_VIOLATIONS"
  echo "   FLEXIBLE warnings: $FLEXIBLE_WARNINGS"
  echo ""
  echo "🔧 FIX STRICT VIOLATIONS BEFORE COMMITTING"
  echo ""
  echo "Quick fixes:"
  echo "  npm run lint -- --fix  # Auto-fix ESLint violations"
  echo "  git diff               # Review auto-fixes"
  echo ""
  echo "Or escalate to premium model:"
  echo "  npm run session:save opencode"
  echo "  opencode --preset claude"
  echo "  npm run session:restore opencode"
  echo ""
  echo "See: .opencode/enforcement/HYBRID_ENFORCEMENT.md"
  echo ""
  exit 1
fi
