/**
 * Barrel exports for src/components/ui
 *
 * Auto-generated by dcyfr fix
 */

export type { InputProps } from './input.js';
export type { LabelProps } from './label.js';
export type {
  SkeletonTextProps,
  SkeletonHeadingProps,
  SkeletonDescriptionProps,
  SkeletonAvatarProps,
  SkeletonBadgeProps,
  SkeletonButtonProps,
  SkeletonMetadataProps,
  SkeletonParagraphsProps,
  SkeletonImageProps,
  SkeletonCardProps,
  SkeletonListProps,
} from './skeleton-primitives.js';
export {
  SkeletonText,
  SkeletonHeading,
  SkeletonDescription,
  SkeletonAvatar,
  SkeletonBadges,
  SkeletonButton,
  SkeletonMetadata,
  SkeletonParagraphs,
  SkeletonImage,
  SkeletonCard,
  SkeletonList,
} from './skeleton-primitives.js';
export type { TextareaProps } from './textarea.js';
export type { TrendingBadgeVariant } from './trending-badge.js';
export { TrendingBadge } from './trending-badge.js';
